import { Permission } from './types';

export const permissions: Permission[] = [
  {
    route: '/students',
    name: 'Crear estudiantes',
    permission: 'create:students',
    description: 'Permite crear nuevos estudiantes.',
  },
  {
    route: '/students',
    name: 'Leer estudiantes',
    permission: 'read:students',
    description: 'Permite ver la información de los estudiantes.',
  },
  {
    route: '/students',
    name: 'Actualizar estudiantes',
    permission: 'update:students',
    description: 'Permite modificar la información de los estudiantes.',
  },
  {
    route: '/students',
    name: 'Eliminar estudiantes',
    permission: 'delete:students',
    description: 'Permite eliminar estudiantes del sistema.',
  },
  {
    route: '/students',
    name: 'Seleccionar documentos',
    permission: 'select:documents',
    description: 'Permite seleccionar documentos relacionados con estudiantes.',
  },
  {
    route: '/enrollments',
    name: 'Crear inscripciones',
    permission: 'create:enrollments',
    description: 'Permite crear nuevas inscripciones.',
  },
  {
    route: '/enrollments',
    name: 'Leer inscripciones',
    permission: 'read:enrollments',
    description: 'Permite ver las inscripciones existentes.',
  },
  {
    route: '/enrollments',
    name: 'Actualizar inscripciones',
    permission: 'update:enrollments',
    description: 'Permite modificar inscripciones existentes.',
  },
  {
    route: '/enrollments',
    name: 'Eliminar inscripciones',
    permission: 'delete:enrollments',
    description: 'Permite eliminar inscripciones.',
  },
  {
    route: '/enrollments',
    name: 'Seleccionar periodos',
    permission: 'select:periods',
    description: 'Permite seleccionar periodos escolares.',
  },
  {
    route: '/enrollments',
    name: 'Crear adeudos',
    permission: 'create:debits',
    description: 'Permite crear adeudos para inscripciones.',
  },
  {
    route: '/enrollments',
    name: 'Leer adeudos',
    permission: 'read:debits',
    description: 'Permite ver los adeudos generados.',
  },
  {
    route: '/enrollments',
    name: 'Actualizar adeudos',
    permission: 'update:debits',
    description: 'Permite modificar adeudos existentes.',
  },
  {
    route: '/enrollments',
    name: 'Eliminar adeudos',
    permission: 'delete:debits',
    description: 'Permite eliminar adeudos.',
  },
  {
    route: '/payments',
    name: 'Seleccionar estudiantes',
    permission: 'select:students',
    description: 'Permite seleccionar estudiantes para pagos.',
  },
  {
    route: '/payments',
    name: 'Seleccionar adeudos',
    permission: 'select:debits',
    description: 'Permite seleccionar adeudos para pagos.',
  },
  {
    route: '/payments',
    name: 'Seleccionar periodos',
    permission: 'select:periods',
    description: 'Permite seleccionar periodos para pagos.',
  },
  {
    route: '/payments',
    name: 'Crear ingresos',
    permission: 'create:incomes',
    description: 'Permite registrar ingresos por pagos.',
  },
  {
    route: '/reports',
    name: 'Reporte de ingresos',
    permission: 'reports:incomes',
    description: 'Permite acceder al reporte de ingresos.',
  },
  {
    route: '/reports',
    name: 'Reporte de adeudos',
    permission: 'reports:debits',
    description: 'Permite acceder al reporte de adeudos.',
  },
  {
    route: '/reports',
    name: 'Reporte de estados de cuenta',
    permission: 'reports:statement-account',
    description: 'Permite acceder al reporte de estados de cuenta.',
  },
  {
    route: '/reports/incomes',
    name: 'Gráfica de ingresos',
    permission: 'reports:chart',
    description: 'Permite ver la gráfica de ingresos.',
  },
  {
    route: '/reports/incomes',
    name: 'Datos de ingresos',
    permission: 'reports:data',
    description: 'Permite ver los datos detallados de ingresos.',
  },
  {
    route: '/reports/debits',
    name: 'Gráfica de adeudos',
    permission: 'reports:chart',
    description: 'Permite ver la gráfica de adeudos.',
  },
  {
    route: '/reports/debits',
    name: 'Datos de adeudos',
    permission: 'reports:data',
    description: 'Permite ver los datos detallados de adeudos.',
  },
  {
    route: '/reports/statement-account',
    name: 'Gráfica de estados de cuenta',
    permission: 'reports:chart',
    description: 'Permite ver la gráfica de estados de cuenta.',
  },
  {
    route: '/reports/statement-account',
    name: 'Datos de estados de cuenta',
    permission: 'reports:data',
    description: 'Permite ver los datos detallados de estados de cuenta.',
  },
  {
    route: '/levels',
    name: 'Crear niveles',
    permission: 'create:levels',
    description: 'Permite crear nuevos niveles.',
  },
  {
    route: '/levels',
    name: 'Leer niveles',
    permission: 'read:levels',
    description: 'Permite ver los niveles existentes.',
  },
  {
    route: '/levels',
    name: 'Actualizar niveles',
    permission: 'update:levels',
    description: 'Permite modificar niveles existentes.',
  },
  {
    route: '/levels',
    name: 'Eliminar niveles',
    permission: 'delete:levels',
    description: 'Permite eliminar niveles.',
  },
  {
    route: '/disciplines',
    name: 'Crear disciplinas',
    permission: 'create:disciplines',
    description: 'Permite crear nuevas disciplinas.',
  },
  {
    route: '/disciplines',
    name: 'Leer disciplinas',
    permission: 'read:disciplines',
    description: 'Permite ver las disciplinas existentes.',
  },
  {
    route: '/disciplines',
    name: 'Actualizar disciplinas',
    permission: 'update:disciplines',
    description: 'Permite modificar disciplinas existentes.',
  },
  {
    route: '/disciplines',
    name: 'Eliminar disciplinas',
    permission: 'delete:disciplines',
    description: 'Permite eliminar disciplinas.',
  },
  {
    route: '/calendars',
    name: 'Crear periodos',
    permission: 'create:periods',
    description: 'Permite crear nuevos periodos.',
  },
  {
    route: '/calendars',
    name: 'Leer periodos',
    permission: 'read:periods',
    description: 'Permite ver los periodos existentes.',
  },
  {
    route: '/calendars',
    name: 'Actualizar periodos',
    permission: 'update:periods',
    description: 'Permite modificar periodos existentes.',
  },
  {
    route: '/calendars',
    name: 'Eliminar periodos',
    permission: 'delete:periods',
    description: 'Permite eliminar periodos.',
  },
  {
    route: '/calendars',
    name: 'Crear horarios',
    permission: 'create:schedules',
    description: 'Permite crear nuevos horarios.',
  },
  {
    route: '/calendars',
    name: 'Leer horarios',
    permission: 'read:schedules',
    description: 'Permite ver los horarios existentes.',
  },
  {
    route: '/calendars',
    name: 'Actualizar horarios',
    permission: 'update:schedules',
    description: 'Permite modificar horarios existentes.',
  },
  {
    route: '/calendars',
    name: 'Eliminar horarios',
    permission: 'delete:schedules',
    description: 'Permite eliminar horarios.',
  },
  {
    route: '/prices',
    name: 'Crear listas de precios',
    permission: 'create:price-lists',
    description: 'Permite crear nuevas listas de precios.',
  },
  {
    route: '/prices',
    name: 'Leer listas de precios',
    permission: 'read:price-lists',
    description: 'Permite ver las listas de precios existentes.',
  },
  {
    route: '/prices',
    name: 'Actualizar listas de precios',
    permission: 'update:price-lists',
    description: 'Permite modificar listas de precios existentes.',
  },
  {
    route: '/prices',
    name: 'Eliminar listas de precios',
    permission: 'delete:price-lists',
    description: 'Permite eliminar listas de precios.',
  },
  {
    route: '/prices',
    name: 'Crear cuotas',
    permission: 'create:fees',
    description: 'Permite crear nuevas cuotas.',
  },
  {
    route: '/prices',
    name: 'Leer cuotas',
    permission: 'read:fees',
    description: 'Permite ver las cuotas existentes.',
  },
  {
    route: '/prices',
    name: 'Actualizar cuotas',
    permission: 'update:fees',
    description: 'Permite modificar cuotas existentes.',
  },
  {
    route: '/prices',
    name: 'Eliminar cuotas',
    permission: 'delete:fees',
    description: 'Permite eliminar cuotas.',
  },
  {
    route: '/discounts',
    name: 'Crear descuentos',
    permission: 'create:discounts',
    description: 'Permite crear nuevos descuentos.',
  },
  {
    route: '/discounts',
    name: 'Leer descuentos',
    permission: 'read:discounts',
    description: 'Permite ver los descuentos existentes.',
  },
  {
    route: '/discounts',
    name: 'Actualizar descuentos',
    permission: 'update:discounts',
    description: 'Permite modificar descuentos existentes.',
  },
  {
    route: '/discounts',
    name: 'Eliminar descuentos',
    permission: 'delete:discounts',
    description: 'Permite eliminar descuentos.',
  },
  {
    route: '/branches',
    name: 'Crear negocios',
    permission: 'create:branches',
    description: 'Permite crear nuevos negocios.',
  },
  {
    route: '/branches',
    name: 'Leer negocios',
    permission: 'read:branches',
    description: 'Permite ver los negocios existentes.',
  },
  {
    route: '/branches',
    name: 'Actualizar negocios',
    permission: 'update:branches',
    description: 'Permite modificar negocios existentes.',
  },
  {
    route: '/branches',
    name: 'Eliminar negocios',
    permission: 'delete:branches',
    description: 'Permite eliminar negocios.',
  },
  {
    route: '/cycles',
    name: 'Crear ciclos',
    permission: 'create:cycles',
    description: 'Permite crear nuevos ciclos.',
  },
  {
    route: '/cycles',
    name: 'Leer ciclos',
    permission: 'read:cycles',
    description: 'Permite ver los ciclos existentes.',
  },
  {
    route: '/cycles',
    name: 'Actualizar ciclos',
    permission: 'update:cycles',
    description: 'Permite modificar ciclos existentes.',
  },
  {
    route: '/cycles',
    name: 'Eliminar ciclos',
    permission: 'delete:cycles',
    description: 'Permite eliminar ciclos.',
  },
  {
    route: '/clip-accounts',
    name: 'Crear cuentas clip',
    permission: 'create:clip-accounts',
    description: 'Permite crear nuevas cuentas clip.',
  },
  {
    route: '/clip-accounts',
    name: 'Leer cuentas clip',
    permission: 'read:clip-accounts',
    description: 'Permite ver las cuentas clip existentes.',
  },
  {
    route: '/clip-accounts',
    name: 'Actualizar cuentas clip',
    permission: 'update:clip-accounts',
    description: 'Permite modificar cuentas clip existentes.',
  },
  {
    route: '/clip-accounts',
    name: 'Eliminar cuentas clip',
    permission: 'delete:clip-accounts',
    description: 'Permite eliminar cuentas clip.',
  },
  {
    route: '/users',
    name: 'Crear usuarios',
    permission: 'create:users',
    description: 'Permite crear nuevos usuarios.',
  },
  {
    route: '/users',
    name: 'Leer usuarios',
    permission: 'read:users',
    description: 'Permite ver los usuarios existentes.',
  },
  {
    route: '/users',
    name: 'Actualizar usuarios',
    permission: 'update:users',
    description: 'Permite modificar usuarios existentes.',
  },
  {
    route: '/users',
    name: 'Eliminar usuarios',
    permission: 'delete:users',
    description: 'Permite eliminar usuarios.',
  },
  {
    route: '/users',
    name: 'Seleccionar políticas',
    permission: 'select:policies',
    description: 'Permite seleccionar políticas de usuario.',
  },
  {
    route: '/policies',
    name: 'Crear políticas',
    permission: 'create:policies',
    description: 'Permite crear nuevas políticas.',
  },
  {
    route: '/policies',
    name: 'Leer políticas',
    permission: 'read:policies',
    description: 'Permite ver las políticas existentes.',
  },
  {
    route: '/policies',
    name: 'Actualizar políticas',
    permission: 'update:policies',
    description: 'Permite modificar políticas existentes.',
  },
  {
    route: '/policies',
    name: 'Eliminar políticas',
    permission: 'delete:policies',
    description: 'Permite eliminar políticas.',
  },
  {
    route: '/policies',
    name: 'Administrar permisos',
    permission: 'management:permissions',
    description: 'Permite la gestión avanzada de permisos.',
  },
];
